basecamp_poll/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import Home

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('admin/', admin.site.urls),

    path('polls/', include('polls.urls'), name='polls'),

    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    
    path('accounts/', include('allauth.urls')),
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
]

polls/urls.py
from django.urls import path
from .views import CreatePollView

app_name = 'polls'
urlpatterns = [
    path('new/', CreatePollView.as_view(), name='create-poll'),
]

users/urls.py
from django.urls import path
from .views import SignUpView, UpgradeView, create_customer_and_subscription

app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('upgrade/', UpgradeView.as_view(), name='upgrade'),
    path('create_subscription/', create_customer_and_subscription, name='create_customer_and_subscription'),
]

polls/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Poll(models.Model):
    name = models.CharField(max_length = 50)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE,
    )
        
    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('lists')

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext as _

class CustomUser(AbstractUser):
    customer = models.ForeignKey(
        'djstripe.Customer', null=True, blank=True, on_delete=models.CASCADE,
        help_text=_("The user's Stripe Customer object, if it exists")
    )
    subscription = models.ForeignKey(
        'djstripe.Subscription', null=True, blank=True, on_delete=models.CASCADE,
        help_text=_("The user's Stripe Subscription object, if it exists")
    )

    def __str__(self):
        return self.username

polls/forms.py
from django.forms import ModelForm
from .models import Poll

class CreatePollForm(ModelForm):

    class Meta:
        model = Poll
        fields = ('name',)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

basecamp_poll/views.py
from django.views.generic import TemplateView
from djstripe.models import Product


class Home(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.all()

        return context

polls/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.conf import settings
from django.views.generic.edit import CreateView

from djstripe.models import Product

from .models import Poll
from .forms import CreatePollForm
from .utils import get_all_bc_projects

class CreatePollView(CreateView):
    form_class = CreatePollForm
    success_url = reverse_lazy('home')
    template_name = 'polls/new_poll.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['STRIPE_PUBLIC_KEY'] = settings.STRIPE_PUBLIC_KEY
        context['products'] = Product.objects.filter(livemode=settings.STRIPE_LIVE_MODE)
        context['basecamp_projects'] = get_all_bc_projects(self.request.user.email) 

        return context

users/views.py
import json
import stripe
import djstripe

from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView
from django.conf import settings
from django.http import JsonResponse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.db import transaction

from .models import CustomUser
from .forms import CustomUserCreationForm
from djstripe.models import Product



class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

class UpgradeView(TemplateView):
    template_name="users/upgrade.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['STRIPE_PUBLIC_KEY'] = settings.STRIPE_PUBLIC_KEY
        context['products'] = Product.objects.filter(livemode=settings.STRIPE_LIVE_MODE)

        return context


@login_required
@require_POST
@transaction.atomic
def create_customer_and_subscription(request):
    """
    Create a Stripe Customer and Subscription object and map them onto the User object
    Expects the inbound POST data to look something like this:
    {
        'email': 'cory@saaspegasus.com',
        'payment_method': 'pm_1GGgzaIXTEadrB0y0tthO3UH',
        'plan_id': 'plan_GqvXkzAvxlF0wR',
    }
    """
    stripe.api_key = djstripe.settings.STRIPE_SECRET_KEY

    # parse request, extract details, and verify assumptions
    request_body = json.loads(request.body.decode('utf-8'))
    
    email = request_body['email']
    assert request.user.email == email  
    
    payment_method = request_body['payment_method']
    plan_id = request_body['plan_id']

    # first sync payment method to local DB to workaround 
    # https://github.com/dj-stripe/dj-stripe/issues/1125
    payment_method_obj = stripe.PaymentMethod.retrieve(payment_method)
    djstripe.models.PaymentMethod.sync_from_stripe_data(payment_method_obj)

    # create customer objects
    # This creates a new Customer in stripe and attaches the default PaymentMethod in one API call.
    customer = stripe.Customer.create(
      payment_method=payment_method,
      email=email,
      invoice_settings={
        'default_payment_method': payment_method,
      },
    )

    djstripe_customer = djstripe.models.Customer.sync_from_stripe_data(customer)

    # create subscription
    subscription = stripe.Subscription.create(
      customer=customer.id,
      items=[
        {
          'plan': plan_id,
        },
      ],
      expand=['latest_invoice.payment_intent'],
    )
    djstripe_subscription = djstripe.models.Subscription.sync_from_stripe_data(subscription)

    # associate customer and subscription with the user
    request.user.customer = djstripe_customer
    request.user.subscription = djstripe_subscription
    request.user.save()

    # return information back to the front end
    data = {
        'customer': customer,
        'subscription': subscription
    }
    return JsonResponse(
        data=data,
    )

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>

  <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

  {% block pre_close_head %}
  {% endblock %}
</head>
<body class="container mx-auto">
  <nav class="flex items-center h-24">
    <ul>
      <li><a class="text-blue-500 hover:text-blue-700" href="{% url 'home' %}">Home</a></li>
    </ul>
  </nav>
  <main>
    {% block content %}
    {% endblock %}
  </main>

  {% block pre_close_body %}
  {% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load socialaccount %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <div class="mb-10">
    <p>Hi {{ user.username }}!</p>
  </div>

  <div class="my-10 p-10">
    <p class="text-lg font-semibold">
      Create new poll 
      <a class="p-3 bg-yellow-300 text-blue-700 hover:text-yellow-300 hover:bg-blue-700" href="{% url 'polls:create-poll' %}">
        +
      </a>
    </p>
  </div>
  
  {% if user.subscription == None %}
    <div class="mb-10">
      <a class="rounded p-5 text-xl border-yellow-400 bg-blue-400 text-white hover:bg-blue-700 hover:text-yellow-400" href="{% url 'users:upgrade' %}">Upgrade</a>
    </div>  
  {% else %}
    <p class="p-5 rounded mb-10">Current Plan - {{ user.subscription }}</p>
  {% endif %}
  
  <div class="mb-10">
    <a class="rounded p-5 text-xl border-yellow-400 bg-yellow-400 text-blue-700 hover:bg-blue-700 hover:text-yellow-400" href="{% url 'logout' %}">logout</a>
  </div>
    
{% else %}

  <div class="p-24 mx-auto border mb-5">
    <p class="mb-10 text-2xl">You are not logged in</p>
    <a class="rounded p-5 text-xl border-yellow-400 bg-yellow-400 text-blue-700 hover:bg-blue-700 hover:text-yellow-400" href="{% provider_login_url 'basecamp' %}">Sign Up | Login (with Basecamp)</a>
  </div>

  <div class="p-24 mx-auto border">
    {% for product in products %}
      <div>
        <p>{{ product.name }}</p>
        {% for plan in product.plan_set.all %}
          <div>
            <p>{{ plan.nickname }}</p>
            <p>{{ plan.human_readable_price }}</p>
          </div>
        {% endfor %}
      </div>
    {% endfor %}
  </div>

{% endif %}
{% endblock %}

templates/polls/new_poll.html
{% extends 'base.html' %}
{% load static %}

{% block title %}New Poll{% endblock %}

{% block content %}
<h1 class="text-4xl font-semibold">New Poll</h2>

<h2 class="text-2xl">Select Project</h2>
{% for project in basecamp_projects %}
<div class="p-3 my-3 border">
    <input type="checkbox" id="{{ project }}" name="{{ project }}">
    <label for="{{ project }}">{{ project }}</label>
</div>
{% endfor %}

<h2 class="text-2xl">Create Poll</h2>
{{ form }}

{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock %}

templates/users/complete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Purchase Complete{% endblock %}

{% block content %}
<h2>Thanks for purchase!</h2>
{% enbblock %}

templates/users/upgrade.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Upgrade{% endblock %}

{% block pre_close_head %}
<script src="https://js.stripe.com/v3/"></script>
<link rel="stylesheet" href="{% static 'css/StripeElements.css' %}">
{% endblock %}

{% block content %}
<h2 class="text-3xl mb-5">Upgrade</h2>

<h3>Select the Plan:</h3>

<div class="flex flex-row">
{% for product in products %}
  <div class="p-3 m-3">
    <p>{{ product.name }}</p>

    {% for plan in product.plan_set.all %}
      <div class="border p-2 my-2">
        <input 
        type="checkbox" 
        name="{{ product.name }}" 
        value="{{product.id}}" 
        id="{{plan.id}}"
        onclick="planSelect('{{product.name}}' ,'{{plan.human_readable_price}}', '{{plan.id}}')">
        <label for="{{plan.id}}">{{ plan.human_readable_price }}</label>
        <p>ID: {{ plan.id }}</p>
        <p>Test:{{ plan.livemode }}</p>
      </div>
    {% endfor %}
  </div>
{% endfor %}
</div>

<div class="w-2/5">
  <form id="subscription-form">
    <div id="card-element" class="MyCardElement">
      <!-- Elements will create input elements here -->
    </div>

    <!-- We'll put the error messages in this element -->
    <div id="card-errors" role="alert"></div>
    <button id="submit" type="submit">Subscribe</button>
  </form>
</div>


{% endblock %}

{% block pre_close_body %}

<script>
  const stripePublicKey = "{{ STRIPE_PUBLIC_KEY }}";
  const customerEmail = "{{ user.username }}";
  const createCustomerUrl = "{% url 'users:create_customer_and_subscription' %}";
</script>

<script src="{% static 'js/stripe.js' %}"></script>

{% endblock %}